# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6e80d63923b4c2b697369ce80494ca508e7400e3a50e56427294a3c947d94617f1a398811ff5c8ad48e30caf524a53e66571e4462eee4ac5d56a1b7b09f7748

test:
  secret_key_base: 2e80c54e84c7bc362de82627d5d76acc5e8c731c48e7be1593c042f8593df45bc1362ac0e61dc718e77d66ae13bf02bbc2cbf7e8416267bde86a44c812b02eed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
